--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ByAlperenS/GiftPackage
build-by-default: true
branches:
- main
projects:
  GiftPackage:
    path: GiftPackage/
    icon: "icon.png"
    libs:
    - src: poggit-orphanage/EconomyS/EconomyAPI
      version: ^3.0.0
...
